##deploy net tools on the server
sudo apt intall net tools
##Apply all new updates to the OS
sudo apt update && sudo apt upgrade -y
##install Python and ansible 
sudo apt install -y openssh-client python3 python3-pip
sudo pip3 install ansible
ansible --version
